.. Review the README on instructions to contribute.
.. Review the style guide to keep a consistent approach to the documentation.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name" -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-DP0-Assemblies-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: DP0 Delegate Assemblies Schedule
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. Use *italics* for tentative topics.

.. Use double-underscore for external links to prevent duplicate explicit target names.

.. list-table:: Schedule and planned content of DP0 Delegate Assemblies
   :header-rows: 1
   :widths: 1 2 2

   * - Date
     - First Hour
     - Second Hour
   * - 2022-07-08
     - `DP0.2 Kick-Off Info Session <https://community.lsst.org/t/dp0-2-kick-off-info-session-slides-pre-recorded-presentation/6846>`_ (beginner)
     - `Introduction to the DP0.2 Time-Domain Data Products <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-9/6898>`__ (intermediate)
   * - 2022-07-22
     - `Catalog Data with the TAP Service <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-22/6930>`__ (beginner)
     - `Time-Domain Catalogs in the TAP Service <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-22/6930>`__ (intermediate)
   * - 2022-08-05
     - Visualizing Image Data (beginner)
     - *breakouts*
   * - 2022-08-19
     - Data Access with the Butler (beginner-intermediate)
     - *breakouts*
   * - 2022-09-02
     - NO ASSEMBLY (long weekend)
     - *none*
   * - 2022-09-16
     - Source Detection and Measurement (beginner)
     - *breakouts*
   * - 2022-09-30
     - Data Visualization (beginner)
     - *breakouts*


Additional delegate assemblies to be posted.
Rows in *italics* are tentative topics.
