.. Review the README on instructions to contribute.
.. Review the style guide to keep a consistent approach to the documentation.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name"  -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-DP0-Assemblies-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: DP0 Delegate Assemblies Schedule
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. Use *italics* for tentative topics.

.. Use double-underscore for external links to prevent duplicate explicit target names.

.. list-table:: Schedule and planned content of DP0 Delegate Assemblies
   :header-rows: 1

   * - Date (Fridays at 9am US Pacific)
     - First Hour Presentation Topic
     - Second Hour Breakouts Topics
     - Chair and Presenter(s)
   * - 2021-07-16
     - `Introduction to DP0, and to the RSP's Notebook and Portal Aspects. <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-16/5689>`__
     - General Q&A. Portal queries Q&A. Python learners. Lightcurves. Large scale structure (LSS).
     - The Community Engagement Team (Melissa Graham)
   * - 2021-07-30
     - `Querying Catalogs with TAP in the Notebook and Portal Aspects. <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-30/5747>`__
     - LSS Working Group. Data visualization. General Q&A. Delegate "New Friends". Single-star lightcurves.
     - The Community Engagement Team (Leanne Guy)
   * - 2021-08-13
     - no assembly (Rubin 2021 Project and Community Workshop)
     - 
     - 
   * - 2021-08-27
     - `Image Query, Retrieval, and Display. <https://community.lsst.org/t/summary-delegate-assembly-fri-aug-27/5845>`__
     - More fun with image display.
     - The Community Engagement Team (Jeff Carlin)
   * - 2021-09-10
     - `Using the Butler for Data Discovery. <https://community.lsst.org/t/summary-delegate-assembly-fri-sep-10/5850>`__
     - More fun with the Butler. General Q&A. Delegate networking.
     - The Community Engagement Team (Alex Drlica-Wagner)
   * - 2021-09-24
     - `LSST Science Pipelines <https://community.lsst.org/t/summary-delegate-assembly-friday-september-24/5884>`__
     - Source detection and measurement. Supernovae. Resolved stellar populations. General Q&A.
     - Yusra AlSayyad (Rubin Algorithms and Pipelines Team)
   * - 2021-10-08
     - `Data Visualization <https://community.lsst.org/t/summary-delegate-assembly-friday-october-8/5960>`__
     - Visualization packages Q&A. DP0 science topics.
     - Keith Bechtol (Rubin Commissioning Team)
   * - 2021-10-22
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assembly-friday-october-22/5984>`__
     - New-to-DP0 tutorial. Supernovae. Large scale structure. Resolved stellar populations. General Q&A.
     - The Community Engagement Team
   * - 2021-11-05
     - `Delegate presenters: Louise Edwards and Kristen Larson <https://community.lsst.org/t/summary-delegate-assembly-fri-nov-5/6071>`__
     - Resolved stellar populations. Large scale strucutre. Extinction in DP0. General Q&A.
     - Louise Edwards, Kristen Larson, and the CET
   * - 2021-11-19
     - `Delegate presenter: Sylvie Dagoret-Campagne <https://community.lsst.org/t/summary-delegate-assembly-fri-nov-19/6127>`__
     - Resolved stellar populations. Large scale strucutre.
     - Sylvie Dagoret-Campagne and the CET
   * - 2021-12-03
     - `Image Processing <https://community.lsst.org/t/summary-delegate-assembly-fri-dec-3/6161>`__
     - Source injection. Deep learning. General Q&A.
     - Andrew Bradshaw (Rubin Camera Subsystem Team)
   * - 2022-01-14
     - no assembly (AAS)
     - 
     - 
   * - 2022-01-28
     - `Special Session on DP0.1: A Half-Year In Review <https://community.lsst.org/t/summary-delegate-assembly-fri-jan-28-20222/6269>`__
     - Large Scale Structure. Variability. Resolved Stellar Populations. General Q&A.
     - The Community Engagement Team
   * - 2022-02-11
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assemblies-fri-feb-11-and-25-2022/6347>`__
     - general Q&A, resolved stellar pops, welcome new delegates!
     - The Community Engagement Team
   * - 2022-02-25
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assemblies-fri-feb-11-and-25-2022/6347>`__
     - general Q&A, resolved stellar pops, background subtraction, machine learning with DP0, truth data
     - The Community Engagement Team
   * - 2022-03-11
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assembly-fri-mar-11-2022/6386>`__
     - general Q&A, truth data, photo-z, orientation for new delegates
     - The Community Engagement Team
   * - 2022-03-25
     - `Photo-z with DP0 Data <https://community.lsst.org/t/summary-delegate-assembly-fri-mar-25-2022/6417>`__
     - general Q&A, PSFs, resolved stellar pops, photo-z
     - Sylvie Dagoret-Campagne and the CET
   * - 2022-04-08
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assembly-fri-apr-8/6457>`__
     - general Q&A, source injection, resolved stellar pops
     - The Community Engagement Team
   * - 2022-04-22
     - `Delegate Breakouts <https://community.lsst.org/t/summary-delegate-assembly-fri-apr-22/6517>`__
     - general Q&A and emergent topics
     - The Community Engagement Team
   * - 2022-05-06
     - Portal Techniques
     - *TBD delegate working groups*
     - Alessandro & Sara, and the CET
   * - 2022-05-20
     - *TBD delegate presenter(s)*
     - *TBD delegate working groups*
     - *TBD*
   * - 2022-06-03
     - *TBD delegate presenter(s)*
     - *TBD delegate working groups*
     - *TBD*
   * - 2022-06-17
     - *TBD delegate presenter(s)*
     - *TBD delegate working groups*
     - *TBD*
